name: Build and Deploy

on:
  push:
    branches:
      - main
      - 'req**'
      - 'feature**'
      - 'release**'
  pull_request:
    branches:
      - main
    paths:
      - 'release**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish_output

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.head.ref == startswith('release', success())

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./publish_output

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: 'compound-interest-calculator'
        package: ./publish_output
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
