name: Deploy Function App

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'compound-interest-calculator'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Ensure correct case for 'Release'
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use
  GH_TOKEN: ${{github.token}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Install jq
        run: sudo apt-get install jq -y
  
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Download build artifact'
        uses: actions/download-artifact@v4
        with:
            name: function-app
            github-token: ${{secrets.GITHUB_TOKEN}}
            repository: jmpompeo/CompoundInterestCalculator

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}/CompoundCalc/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
