name: Deploy Function App

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'compound-interest-calculator'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Ensure correct case for 'Release'
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      - name: List Content of Output
        run: ls -R output

      - name: 'Download build artifact'
        uses: actions/download-artifact@v4
        with:
            name: function-app
            path: ./output

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}/CompoundCalc/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
