name: Deploy Function App

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'compound-interest-calculator'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'CompoundInterestCalculator/CompoundCalc/bin/Release/net8.0' # Correct path
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'List Directory Contents for Debugging'
        run: |
          dir
          dir CompoundInterestCalculator
          dir CompoundInterestCalculator/CompoundCalc
          dir CompoundInterestCalculator/CompoundCalc/bin
          dir CompoundInterestCalculator/CompoundCalc/bin/Release

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd '${{ github.workspace }}/CompoundInterestCalculator/CompoundCalc'
          dotnet build --configuration Release --output ${{ github.workspace }}/CompoundInterestCalculator/CompoundCalc/bin/Release/net8.0/output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ github.workspace }}/CompoundInterestCalculator/CompoundCalc/bin/Release/net8.0/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
