name: Deploy Function App

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'compound-interest-calculator'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'CompoundCalc/bin/Release/net8.0/output'

jobs:
  build-and-deploy:
    runs-on: windows-latest    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd 'CompoundCalc'
          dotnet build --configuration Release --output bin/Release/net8.0/output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
